export const reportType = ["Crime", "Accident", "Hazards", "Arson/Fire"];
export const severityLevels = ["Minor", "Moderate", "Major", "Severe"];

export const crimes = [
  "Robbery",
  "Burglary",
  "Assault",
  "Fraud",
  "Vandalism",
  "Kidnapping",
  "Homicide",
  "Cybercrime",
  "Shoplifting",
  "Identity Theft",
  "Drug Trafficking",
  "Domestic Violence",
  "Arson",
  "Carjacking",
  "Forgery",
  "Human Trafficking",
  "Embezzlement",
  "Harassment",
  "Public Intoxication",
];

export const locationOptions = [
  "Bacayao Norte",
  "Bacayao Sur",
  "Bolosan",
  "Bonuan Binloc",
  "Bonuan Boquig",
  "Bonuan Gueset",
  "Calmay",
  "Carael",
  "Caranglaan",
  "Herrero",
  "Lasip Chico",
  "Lasip Grande",
  "Lomboy",
  "Lucao",
  "Malued",
  "Mamalingling",
  "Mangin",
  "Mayombo",
  "Pantal",
  "Poblacion Oeste",
  "Pogo Chico",
  "Pogo Grande",
  "Pugaro Suit",
  "Salapingao",
  "Salisay",
  "Tambac",
  "Tapuac",
  "Tebeng",
];

export const accidentTypes = [
  "Car accidents",
  "Motorcycle accidents",
  "Bicycle accidents",
  "Pedestrian accidents",
  "Slips, trips, and falls",
  "Machinery accidents",
  "Falling objects",
  "Electrical accidents",
  "Falls at home",
  "Burns",
  "Poisoning",
  "Choking",
  "Earthquakes",
  "Hurricanes",
  "Tornadoes",
  "Floods",
  "Sports injuries",
  "Water-related accidents",
  "Playground accidents",
  "Chemical spills",
  "Explosions",
  "Structural failures",
  "Public transportation accidents",
  "Accidents in public spaces",
  "Amusement park accidents",
  "Lightning strikes",
  "Animal attacks",
  "Helicopter accidents",
  "Drone accidents",
  "Boat accidents",
];

export const hazardList = [
  "Physical Hazards",
  "Chemical Hazards",
  "Biological Hazards",
  "Ergonomic Hazards",
  "Radiation Hazards",
  "Psychosocial Hazards",
  "Environmental Hazards",
  "Electrical Hazards",
  "Fire Hazards",
];

export const arsonFireTypes = [
  "Incendiary Fire",
  "Accidental Fire",
  "Electrical Fire",
  "Wildfire",
  "Arson for Profit",
  "Vehicle Arson",
  "Structure Fire",
  "Arson for Vandalism",
  "Arson for Revenge",
  "Arson for Hate Crimes",
  "Molotov Cocktail",
  "Spontaneous Combustion",
  "Gasoline Fire",
  "Industrial Fire",
  "Terrorist Arson",
  "Pyromania",
];
